// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gshojiodjzkqblgjlhts.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdzaG9qaW9kanprcWJsZ2psaHRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMTUzMDYsImV4cCI6MjA2Mjg5MTMwNn0.mnSTCxygY-mm7QmXIdX4_M3EiVxEnIgNAUy3xo_WTOM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);